<a href="https://colab.research.google.com/github/vyshakhRemesh/statistics_CDAC/blob/main/Day_7_Sampling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("students.csv")

In [ ]:
df

,student_id,age,gender,academic_level,study_hours,self_study_hours,online_classes_hours,social_media_hours,gaming_hours,sleep_hours,...,exercise_minutes,caffeine_intake_mg,part_time_job,upcoming_deadline,internet_quality,mental_health_score,focus_index,burnout_level,productivity_score,exam_score
0,1,18,Other,High School,7.64,1.56,2.20,3.05,2.19,6.52,...,81,38,1,0,Good,10,43.05,31.77,73.65,50.16
1,2,18,Other,High School,2.21,2.22,2.10,1.65,2.55,5.97,...,111,339,0,0,Good,3,15.92,37.00,13.70,1.00
2,3,22,Male,High School,3.45,0.00,0.29,1.34,2.08,8.39,...,68,266,0,1,Good,8,27.39,34.37,45.15,18.30
3,4,17,Other,High School,5.75,2.08,3.01,2.27,2.20,6.31,...,113,480,1,1,Poor,3,22.31,77.31,20.92,9.37
4,5,19,Other,High School,6.83,1.72,3.33,2.65,0.70,8.01,...,121,24,1,0,Good,8,38.11,39.53,59.23,27.81
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,4996,20,Other,Undergraduate,3.93,1.42,0.54,2.58,2.62,9.30,...,113,496,0,0,Good,9,35.55,33.24,48.83,22.51
4996,4997,24,Male,High School,4.00,0.00,3.00,4.45,2.47,6.42,...,146,411,0,1,Poor,5,16.87,59.07,23.32,2.00
4997,4998,22,Male,Undergraduate,5.63,2.52,2.89,3.58,1.07,6.65,...,123,306,0,1,Good,7,23.85,47.72,41.09,27.89
4998,4999,17,Male,Undergraduate,3.58,2.83,1.53,5.88,1.28,7.36,...,54,304,1,1,Good,4,13.04,58.90,12.62,3.63
4999,5000,22,Other,Undergraduate,5.60,4.14,2.17,3.05,2.74,6.38,...,24,219,0,1,Good,3,29.98,61.01,34.72,10.76

In [ ]:
sample_random=df.sample(n=10)
sample_random

,student_id,age,gender,academic_level,study_hours,self_study_hours,online_classes_hours,social_media_hours,gaming_hours,sleep_hours,...,exercise_minutes,caffeine_intake_mg,part_time_job,upcoming_deadline,internet_quality,mental_health_score,focus_index,burnout_level,productivity_score,exam_score
4921,4922,21,Male,High School,6.83,3.13,2.24,2.00,1.94,9.42,...,110,410,0,0,Average,3,43.63,20.79,56.96,29.88
2134,2135,21,Male,High School,3.81,3.66,1.29,5.94,1.43,7.18,...,50,289,1,0,Poor,5,20.33,52.21,27.79,13.38
2342,2343,21,Other,Undergraduate,4.17,2.19,1.20,1.96,3.02,5.74,...,114,438,1,1,Average,3,16.71,65.75,22.20,3.15
787,788,25,Male,High School,2.66,4.31,1.38,3.12,0.00,8.29,...,74,394,0,1,Average,2,24.09,40.08,12.95,10.01
1264,1265,25,Male,Postgraduate,2.61,1.53,0.00,4.06,1.89,5.22,...,29,441,0,1,Poor,8,25.56,59.46,30.53,16.79
4861,4862,23,Female,Postgraduate,0.00,3.74,0.20,6.23,4.36,9.43,...,76,438,0,1,Poor,5,14.63,23.53,19.99,12.08
3869,3870,20,Male,Undergraduate,7.22,1.68,1.68,5.24,0.87,5.60,...,62,76,0,0,Good,5,32.39,37.90,54.66,31.69
3745,3746,24,Male,Undergraduate,5.94,1.97,1.85,2.78,2.44,4.71,...,67,174,1,0,Average,1,14.32,52.07,29.41,9.26
4067,4068,22,Male,High School,6.18,3.96,1.41,4.43,0.71,7.23,...,77,103,1,0,Poor,9,39.78,37.35,66.41,41.60
4558,4559,16,Other,High School,4.02,3.09,4.08,2.39,1.52,6.43,...,2,182,0,1,Good,2,25.30,43.50,16.64,11.84

In [ ]:
systematic_sample=df.iloc[::5]
systematic_sample

,student_id,age,gender,academic_level,study_hours,self_study_hours,online_classes_hours,social_media_hours,gaming_hours,sleep_hours,...,exercise_minutes,caffeine_intake_mg,part_time_job,upcoming_deadline,internet_quality,mental_health_score,focus_index,burnout_level,productivity_score,exam_score
0,1,18,Other,High School,7.64,1.56,2.20,3.05,2.19,6.52,...,81,38,1,0,Good,10,43.05,31.77,73.65,50.16
5,6,25,Male,Undergraduate,2.21,3.50,1.69,4.47,1.56,8.34,...,110,288,0,1,Average,8,30.52,33.64,36.20,18.53
10,11,25,Other,Postgraduate,2.28,2.69,2.95,3.27,0.60,6.40,...,146,24,1,1,Poor,8,19.21,48.25,24.48,11.65
15,16,20,Other,Undergraduate,3.85,3.09,3.36,2.13,2.75,5.09,...,97,413,0,0,Average,4,21.66,41.97,26.95,14.69
20,21,23,Male,Undergraduate,9.31,4.04,3.06,1.46,1.23,7.74,...,71,118,1,0,Good,10,60.72,31.88,91.52,64.09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4975,4976,21,Male,Undergraduate,2.09,2.27,0.44,3.22,3.60,6.08,...,11,201,1,0,Average,8,20.66,50.47,22.96,5.77
4980,4981,25,Male,Postgraduate,2.86,2.17,1.57,2.58,2.81,7.73,...,29,151,0,1,Average,5,22.71,39.16,23.36,10.34
4985,4986,18,Female,High School,5.22,3.89,0.82,4.23,2.25,5.49,...,120,155,1,0,Average,5,20.85,53.68,38.10,19.65
4990,4991,22,Male,Undergraduate,5.54,3.07,0.40,5.26,0.00,7.56,...,118,184,1,1,Good,7,36.05,47.66,49.61,25.25
4995,4996,20,Other,Undergraduate,3.93,1.42,0.54,2.58,2.62,9.30,...,113,496,0,0,Good,9,35.55,33.24,48.83,22.51

In [ ]:
from sklearn.model_selection import train_test_split

sample_data,remaining=train_test_split(df,test_size=0.8,stratify=df['gender'],random_state=1)
sample_data['gender'].value_counts()

gender
Male      344
Other     330
Female    326
Name: count, dtype: int64

In [ ]:
cluster_sample=df[df['internet_quality']=='Good']
cluster_sample

,student_id,age,gender,academic_level,study_hours,self_study_hours,online_classes_hours,social_media_hours,gaming_hours,sleep_hours,...,exercise_minutes,caffeine_intake_mg,part_time_job,upcoming_deadline,internet_quality,mental_health_score,focus_index,burnout_level,productivity_score,exam_score
0,1,18,Other,High School,7.64,1.56,2.20,3.05,2.19,6.52,...,81,38,1,0,Good,10,43.05,31.77,73.65,50.16
1,2,18,Other,High School,2.21,2.22,2.10,1.65,2.55,5.97,...,111,339,0,0,Good,3,15.92,37.00,13.70,1.00
2,3,22,Male,High School,3.45,0.00,0.29,1.34,2.08,8.39,...,68,266,0,1,Good,8,27.39,34.37,45.15,18.30
4,5,19,Other,High School,6.83,1.72,3.33,2.65,0.70,8.01,...,121,24,1,0,Good,8,38.11,39.53,59.23,27.81
7,8,17,Male,High School,8.77,3.78,2.09,1.76,3.13,7.62,...,135,379,1,0,Good,1,31.98,45.98,45.04,19.89
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4994,4995,21,Female,High School,2.48,3.65,2.15,4.39,1.96,5.34,...,86,245,0,0,Good,10,30.93,33.79,45.74,26.31
4995,4996,20,Other,Undergraduate,3.93,1.42,0.54,2.58,2.62,9.30,...,113,496,0,0,Good,9,35.55,33.24,48.83,22.51
4997,4998,22,Male,Undergraduate,5.63,2.52,2.89,3.58,1.07,6.65,...,123,306,0,1,Good,7,23.85,47.72,41.09,27.89
4998,4999,17,Male,Undergraduate,3.58,2.83,1.53,5.88,1.28,7.36,...,54,304,1,1,Good,4,13.04,58.90,12.62,3.63
4999,5000,22,Other,Undergraduate,5.60,4.14,2.17,3.05,2.74,6.38,...,24,219,0,1,Good,3,29.98,61.01,34.72,10.76